# Generated by Django 5.0.10 on 2025-03-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('advanced', 'Advanced Plan')],
            },
        ),
    ]
