# Generated by Django 5.0.10 on 2025-03-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('advanced', 'Advanced Plan'), ('basic_ai', 'Basic AI plan')]},
        ),
    ]
