# Generated by Django 5.0.10 on 2025-03-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
    ]
