# Generated by Django 5.0.10 on 2025-03-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='acitve',
            new_name='active',
        ),
    ]
